# Numpy,Pyomo and Linear Algebra

## Numpy



In [29]:
import numpy as np

# scalar
s = 12.0

# vectors
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

print("v =", v)
print("w =", w)
print("vnp.dot(v, w))
print(v * v)

v = [1 2 3]
w = [4 5 6]
32
[1 4 9]


### Scalar mulitplication

In [5]:
s = 12.0
print(s * v)

[12. 48. 60.]


### Matrix operations

In [7]:
A = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
])

print(A)

print(A.T)


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [8]:
print(np.dot(A, v))

[24. 54. 84.]


## Pyomo

In [22]:
import pyomo.environ as pyo

m = pyo.ConcreteModel()

m.x = m.Var(3)
m.y = sum(v[j] * m.x[j] for j in range(3))

TypeError: '_generic_component_decorator' object is not subscriptable